config:
  models_path: './models/'
  gamma: 0.9
  epsilon_init: 0.9
  epsilon_min: 0.0001
  epsilon_decay: 0.95
  lr: 0.001
  max_memory: 1000000
  batch_size: 4096
  game_width: 200
  game_height: 200
  block_size: 20
  green_apples_count: 2
  red_apples_count: 1

