config:
  debug: false
  models_path: './models/'
  gamma: 0.95
  epsilon_init: 0.9
  epsilon_min: 0.2 # Keep it high enough to keep exploring during training, even if the
  epsilon_decay: 0.995
  lr: 0.01 # Keep it high enough to actually learn
  max_memory: 1000000
  batch_size: 1024
  game_width: 800
  game_height: 800
  block_size: 80
  alive_reward: -0.5
  death_reward: -100
  green_apple_reward: 5
  red_apple_reward: -5
